AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Image:
    Description: Name of ecr repo image
    Type: String
  ClusterName:
    Description: Name of ECS cluster
    Type: String
  Family:
    Description: task definition family
    Type: String  
  ServiceName:
    Description: ECS service name
    Type: String  


Resources:
  taskdefinition: 
    Type: AWS::ECS::TaskDefinition
    Properties: 
      RequiresCompatibilities:
        - "EC2"
      Family: !Ref Family
    
      ContainerDefinitions: 
        - 
          Name: "my-app"

          Image: !Ref Image
          Cpu: "256"
          Memory: "512"
          Essential: true
          PortMappings:
            -
              ContainerPort: "9005"
              Protocol: "tcp"

  ECSService: 
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref ClusterName
      ServiceName: !Ref  ServiceName
      LoadBalancers:
         - TargetGroupArn: "arn:aws:elasticloadbalancing:us-east-1:360913885216:targetgroup/craft-tg/cb5e42a839258a17" 
           ContainerPort: "9005"
           ContainerName: "my-app"
      DesiredCount: "1"
      TaskDefinition: 
        Ref: "taskdefinition"
 

          
 
        
